# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'
Vagrant.require_version ">= 1.6.0"

$instance_name="node-%01d"
$instance_ip="172.17.8.3%01d"
$num_instances=5

$coreos_channel="alpha"
$coreos_name="coreos-" + $coreos_channel 
$coreos_version="723.0.0"

$virtualbox_gui = false
$virtualbox_memory = 1024
$virtualbox_cpus = 1

# makes all scripts executable & move the cloudinit file to the right place
$provision_script = <<SCRIPT
mv /tmp/user-data/* /var/lib/coreos-vagrant/ && find /home/core/* -name '*.sh' -type f -exec chmod 0755 '{}' ';'
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = $coreos_name
    config.vm.box_version = $coreos_version
    config.vm.box_url = "http://" + $coreos_channel + ".release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

    (1..$num_instances).each do |i|
        config.vm.define vm_name = $instance_name % i do |config|
            config.vm.hostname = vm_name
            config.vm.network :private_network, ip: $instance_ip % i
            config.vm.provider :virtualbox do |virtualbox|
                virtualbox.gui = $virtualbox_gui
                virtualbox.memory = $virtualbox_memory
                virtualbox.cpus = $virtualbox_cpus
            end

            # sync files
            config.vm.synced_folder "bin", "/home/core/bin"
            config.vm.synced_folder "user-data", "/tmp/user-data"

            config.vm.provision :shell, :inline => $provision_script
        end
    end
end
