#cloud-config

coreos:
    units:
       - name: kubernetes.service
         command: start
         enable: true
         content: |
             [Unit]
             Description=Kubernetes Start script
             Requires=etcd2.service fleet.service
             After=etcd2.service fleet.service

             [Service]
             Type=oneshot
             RemainAfterExit=yes
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-download.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-proxy.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-kubelet.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-apiserver.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-scheduler.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-controller-manager.service
             ExecStart=/usr/bin/fleetctl start --no-block /home/core/fleet-units/kube-register.service
             ExecStartPost=/home/core/bin/create-k8s-env.sh
             Restart=no

             [Install]
             WantedBy=multi-user.target

       - name: inaetics-k8s-services.service
         command: start
         enable: true
         content: |
             [Unit]
             Description=INAETICS demonstrator Kubernetes services
             Requires=kubernetes.service
             After=inaetics-k8s-controllers.service

             [Service]
             Type=oneshot
             RemainAfterExit=yes
             EnvironmentFile=/etc/kubernetes.env
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/ace-provisioning-service.json
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/inaetics-viewer-service.json
             Restart=no

             [Install]
             WantedBy=multi-user.target

       - name: inaetics-k8s-controllers.service
         command: start
         enable: true
         content: |
             [Unit]
             Description=INAETICS demonstrator Kubernetes controllers
             Requires=kubernetes.service
             After=kubernetes.service
             Before=inaetics-k8s-services.service

             [Service]
             Type=oneshot
             RemainAfterExit=yes
             EnvironmentFile=/etc/kubernetes.env
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/ace-provisioning-controller.json
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/inaetics-datastore-viewer-controller.json
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/inaetics-processor-controller.json
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/inaetics-producer-controller.json
             ExecStart=/opt/bin/kubectl create -f /home/core/inaetics-demo/k8s/inaetics-queue-controller.json
             Restart=no

             [Install]
             WantedBy=multi-user.target

###EOF###
