#cloud-config

coreos:
  units:
    - name: docker-registry.service
      command: start
      runtime: no
      enable: true
      content: |
        [Unit]
        Description=Docker Registry Service
        Requires=docker.service
        After=docker.service

        [Service]
        ExecStart=/usr/bin/docker run -p 5000:5000 registry
        ExecStartPost=/bin/bash -c "cd /home/core/inaetics-demo; for I in node-*; do ../bin/docker-build.sh $I; done"
        TimeoutStartSec=0
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target

    - name: docker-registry-announce.service
      command: start
      runtime: no
      enable: true
      content: |
        [Unit]
        Description=Docker Registry Announce
        BindsTo=docker-registry.service

        [Service]
        ExecStart=/bin/sh -c "while true; do etcdctl set /inaetics/docker-registry-service/%m 172.17.8.20:5000 --ttl 60; sleep 45; done"
        ExecStopPost=/usr/bin/etcdctl rm /inaetics/docker-registry-service/%m

        [Install]
        WantedBy=multi-user.target

###EOF###
