apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:v1.0.6
    command:
    - /hyperkube
    - proxy
    - --master=https://172.17.8.20
    - --kubeconfig=/opt/kubernetes/cluster-kubeconfig.yaml
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: ssl-certs
        readOnly: true
      - mountPath: /opt/kubernetes/cluster-kubeconfig.yaml
        name: kubeconfig
        readOnly: true
      - mountPath: /opt/ssl
        name: ssl-certs-kubernetes
        readOnly: true
  volumes:
    - name: ssl-certs
      hostPath:
        path: /usr/share/ca-certificates
    - name: kubeconfig
      hostPath:
        path: /home/core/k8s/cluster-kubeconfig.yaml
    - name: ssl-certs-kubernetes
      hostPath:
        path: /opt/ssl

###EOF###
